networks:
  mysql_database:
    external: true
    name: mysql_database

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
services:

### MySQL ################################################
    mysql_80:
      platform: linux/amd64 # Use this line for M1 Mac
      container_name: mysql_80
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - mysql_database